import os
import time
import numpy as np
import pandas as pd  # <-- ADDED FOR CSV MANAGEMENT
import matplotlib.pyplot as plt
from itertools import product
from os import getenv
from qat.qlmaas.connection import QLMaaSConnection
import re 

# This is the script to retrieve asynchronously the remote result indicating n_atoms, job_id and
# benchmark file path

# --- 0. INITIAL SETUP ---
N_ATOMS = 15
#JOB_ID = "SJob214087"  # Remember to update this ID with the one generated by bench.py
#JOB_ID = "SJob213552"


#IMPORTANTE: qui non usare nome del target file nel filename, dalla istanza 15x15 in poi sì!
#JOB_ID = "SJob214184" #To do: evaluate 10x10 istance with aggressive parametrization. 
#JOB_ID = "SJob214241"
FITNESS_TYPE = "Improved_Topological_MAE" # Change to "MSE" when testing the other metric

JOB_ID = "SJob214728"
#FILE_PATH = "./my_QUBO_instances/scaling_tests/friendly/global_friendly_5x5_d50_s100.npz"
#FILE_PATH = "./my_QUBO_instances/scaling_tests/friendly/global_friendly_6x6_d46.7_s100.npz"
#FILE_PATH = "./my_QUBO_instances/scaling_tests/jade_udg/jade_udg_10x10_R12_s52.npz"
FILE_PATH = "./my_QUBO_instances/scaling_tests/jade_udg/jade_udg_15x15_R12_s57.npz"


OUTPUT_CSV = "./new_csv/experiment_registry_15x15.csv"




# --- 1. HELPER FUNCTIONS (LOADER AND CLASSICAL SOLVER) ---
def load_hamburg_matrix(file_path):
    """Reads the QUBO matrix from the benchmark .npz file."""
    try:
        with np.load(file_path, allow_pickle=True) as data:
            i_indices = data['i']
            j_indices = data['j']
            weights = data['Jij']
            
            n_nodes = int(max(np.max(i_indices), np.max(j_indices))) + 1
            Q = np.zeros((n_nodes, n_nodes))
            
            for r, c, w in zip(i_indices, j_indices, weights):
                r, c = int(r), int(c)
                Q[r, c] = w
                if r != c:
                    Q[c, r] = w
            return Q
    except Exception as e:
        print(f"Error loading the matrix: {e}")
        return None

def find_classical_ground_state(Q):
    """Executes a classical Brute Force calculation to find the exact optimal solution."""
    print("  -> Calculating the True Mathematical Ground State (Brute Force)...")
    min_energy = float('inf')
    ground_states = []
    
    for bits in product([0, 1], repeat=len(Q)):
        x = np.array(bits)
        energy = x.T @ Q @ x
        if energy < min_energy:
            min_energy = energy
            ground_states = ["".join(map(str, bits))]
        elif energy == min_energy:
            ground_states.append("".join(map(str, bits)))
            
    return ground_states, min_energy

# --- 2. CLASSICAL PROCESSING ---
Q = load_hamburg_matrix(FILE_PATH)
if Q is None:
    exit()

true_ground_states, true_energy = find_classical_ground_state(Q)
print(f"  -> [OK] Found {len(true_ground_states)} mathematical optimal solutions with energy: {true_energy:.4f}")
print(f"True ground state:   {true_ground_states}")

# --- 3. RETRIEVING QUANTUM JOB ---
print(f"Connecting to Jülich to search for Job: {JOB_ID}")
try:
    connection = QLMaaSConnection()
    if JOB_ID == "":
        raise RuntimeError("specify the environment variable JOB_ID")

    status = connection.get_status(JOB_ID)
    results = connection.get_result(JOB_ID)
    print(f"  -> Current Job status: {status}")
    
except Exception as e:
    print(f"\nError during retrieval. Make sure the ID is correct. Details: {e}")
    exit()

if results is None:
    raise Exception("No results obtained from the emulator.")

# Extract probability with Bulletproof Regex Parser
samples = {}
for sample in results.raw_data:
    raw_str = str(sample.state)
    bits_only = re.sub(r'[^01]', '', raw_str)
    bitstring = bits_only.zfill(N_ATOMS)    
    samples[bitstring] = sample.probability

# --- CORRECTLY REINTEGRATED SORTING ---
samples = dict(sorted(samples.items(), key=lambda item: item[1], reverse=True))

# --- CALCULATING HIGHEST PROBABILITY STATE ENERGY ---
if len(samples) > 0:
    top_state_bitstring = list(samples.keys())[0]
    top_state_prob = samples[top_state_bitstring]
    x_top = np.array([int(b) for b in top_state_bitstring])
    top_state_energy = x_top.T @ Q @ x_top
else:
    top_state_bitstring = None
    top_state_prob = 0.0
    top_state_energy = 0.0

# Final console check
print("\n--- ENERGY ANALYSIS ---")
print(f"Most probable sampled state: {top_state_bitstring}")
print(f"  -> Probability: {top_state_prob:.4f}")
print(f"  -> Calculated Energy: {top_state_energy:.4f}")
print(f"  -> Energy gap from Ground State: {top_state_energy - true_energy:.4f}\n")

# =====================================================================
# --- NEW LOGIC: UNIFIED CSV REGISTRY UPDATE ---
# =====================================================================


# 1. Prepare the quantum data package to save
quantum_data = {
    "Top_State_QPU": top_state_bitstring,
    "Top_Prob_QPU": round(top_state_prob, 4),
    "Energy_QPU": round(top_state_energy, 4),
    "Gap_From_GS": round(top_state_energy - true_energy, 4),
    "Target_Reached": "YES" if top_state_bitstring in true_ground_states else "NO"
}

# 2. Dynamically unpack the metadata sent by Jülich (results.meta_data)
if hasattr(results, 'meta_data') and results.meta_data is not None:
    # Transform into a standard dictionary if it isn't already
    meta_dict = dict(results.meta_data)
    for key, value in meta_dict.items():
        # Create clean columns like "Meta_execution_time", "Meta_backend", etc.
        quantum_data[f"Meta_{key}"] = value

# 3. Smart writing to the CSV file
if os.path.exists(OUTPUT_CSV):
    df_history = pd.read_csv(OUTPUT_CSV)
    
    # Check if bench.py has already created the row by inserting this specific Job ID
    if "Juelich_Job_ID" in df_history.columns and JOB_ID in df_history["Juelich_Job_ID"].values:
        # Find the index of the pre-existing row to merge the data
        idx_row = df_history[df_history["Juelich_Job_ID"] == JOB_ID].index[0]
        
        # Inject the new quantum data and metadata into their respective columns in that row
        for column, value in quantum_data.items():
            df_history.at[idx_row, column] = value
        print(f"[CSV] Existing row for Job {JOB_ID} successfully enriched with hardware metadata.")
    else:
        # If the Job ID is not found (e.g., you ran retrieve without going through bench.py), create a new row
        new_data = {
            "Timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "Instance": os.path.basename(FILE_PATH),
            "N_Nodes": N_ATOMS,
            "Juelich_Job_ID": JOB_ID,
            "Fitness_Metric": FITNESS_TYPE
        }
        new_data.update(quantum_data)
        df_history = pd.concat([df_history, pd.DataFrame([new_data])], ignore_index=True)
        print(f"[CSV] Job {JOB_ID} not previously registered. Created a new dedicated row.")
else:
    # If the CSV file does not exist yet, create it from scratch
    new_data = {
        "Timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "Instance": os.path.basename(FILE_PATH),
        "N_Nodes": N_ATOMS,
        "Juelich_Job_ID": JOB_ID,
        "Fitness_Metric": FITNESS_TYPE
    }
    new_data.update(quantum_data)
    df_history = pd.DataFrame([new_data])
    print(f"[CSV] File '{OUTPUT_CSV}' not found. Generated a new archive from scratch.")

# Final save to disk (executed BEFORE the plot so you don't lose data if you close the window early)
df_history.to_csv(OUTPUT_CSV, index=False)
print(f"[OK] Archive '{OUTPUT_CSV}' updated and synchronized.\n")
# =====================================================================

# --- 4. HYBRID PLOT (QPU + MATH) ---
print("  -> Generating Quantum Histogram Plot...")
top_samples = dict(list(samples.items())[:30]) 

bar_colors = ['green' if bit in true_ground_states else 'blue' for bit in top_samples.keys()]

plt.figure(figsize=(14, 7))
bars = plt.bar(top_samples.keys(), top_samples.values(), color=bar_colors, alpha=0.7)

from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='blue', alpha=0.7, label='QPU Measurement (False Local Minima)'),
    Patch(facecolor='green', alpha=0.7, label=f'True Mathematical Ground State ({true_energy:.2f})')
]
plt.legend(handles=legend_elements)

plt.xlabel("Measured Configurations (Bitstrings)")
plt.ylabel("Probability (QPU Frequency)")
file_name = os.path.basename(FILE_PATH)

# Title updated dynamically with the type of fitness used
plt.title(f"Top 30 Emulated vs Math Optimal - {file_name} ({N_ATOMS} atoms) | Fit: {FITNESS_TYPE}")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

for gs in true_ground_states:
    if gs in top_samples:
        print(f"True Ground State {gs} found in Top 30 at rank {list(top_samples.keys()).index(gs) + 1} with probability {top_samples[gs]:.4f}")
    elif gs in samples:
        print(f"True Ground State {gs} found outside Top 30 (Probability: {samples[gs]:.6f})")
    else:
        print(f"True Ground State {gs} NEVER sampled by QPU (Probability 0.0)")

plt.show()

print("\nRaw metadata printed from Job:")
print(results.meta_data)